package rules.engine.set.ruleset1
import com.alibaba.fastjson.JSONObject

rule "r_text_exist_1"
when
    $fact:JSONObject(getString("text") != null)
then
    $fact.put("passd", "1");
    System.out.println("车号为: " + $fact.getString("text"));
end


rule "r_text_exist_3"
when
    $fact:JSONObject(getInteger("weight") != null && getInteger("weight") >= 60)
then
    $fact.put("overweight", 1);
    System.out.println("该车超重");
end


rule "r_text_exist_4"
    salience 10
    no-loop true
when
    $fact:JSONObject(getString("hasGood") != null && getString("hasGood").equals("0"))
then
    $fact.put("not_good", 1);
    $fact.put("passd", "0");
    System.out.println("该车无货");
    update($fact);
end


rule "r_text_not_in_1"
    salience 5
when
    $fact:JSONObject(getString("passd") != null && getString("passd").equals("0"))
then
    System.out.println("该车无法正确出车");
end